delete from _MenuTableMap;
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('report','account_balance','科目余额表','FormAccountBalance',128,1);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('report','balance_sheet','资产负债表','FormBalanceSheet',256,2);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('report','profit_sheet','利润表','FormProfitSheet',0,3);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('report','sp_udefreport_voucher_udef','数量统计表','FormUdefReport',1024,4);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('account','voucher_input','凭证录入','FormVoucher',32,1);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('account','voucher_list','凭证查询','FormVoucherList',64,2);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('account','begin_balance','期初录入','FormBeginBalance',16,3);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('account','carriedforward','月度结转','FormCarriedForward',0,4);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('account','settle','结账','',512,5);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('base_setting','access_right','权限设置','FormAccesRight',0,5);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('base_setting','account_subject','科目设置','FormAccountSubject',4,1);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('base_setting','accountitem','辅助核算','FormAccountItem',0,2) ;
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('base_setting','auxiliary_manager','其它设置','FormAuxiliary',8,5);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('base_setting','carriedforward_template','结转方式设置','FormCarriedForwardTemplate',0,3);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('base_setting','user_list','用户列表','FormUser',2,4);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('other','menu_edit','菜单设置','FormMenuEdit',2048,2);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('other','udeftemplate_list','自定义模板','FormUdefTemplate',4096,1);
insert into _MenuTableMap (_group, _name, _header, _financeForm,_mask,_index) values('other','_InterfaceExec','引入凭证','FormInterface',8192,3);
